### ISSUE TITLE
Programming Question: Ref and anonymous function

### ISSUE THREAD

**Issue by EcoEditor** [PeturDarri/GenericEventBus#2]
Hey @PeturDarri 

Thank you for this tool! 
I have a programming question regarding subscription to the event:

in the start function, I call:

GenericEventBus<IEvent>.Instance.SubscribeTo<RequestTryChangeStateEvent>(Handler);

then another method is subscribed:

        private void Handler(ref RequestTryChangeStateEvent eventdata)
        {
            throw new NotImplementedException();
        }

But I'd like to do that:

            GenericEventBus<IEvent>.Instance.SubscribeTo<RequestTryChangeStateEvent>(ref args =>
            {
                var physicsState = args.RequestedPhysicsState;
                TryChangePhysicsState(physicsState);
            });

but I get an error on the args parameter, it says: "Parameter 'args' must be declared as 'ref'

I understand it's not possible to use the ref parameter in the anonymous function since this function manipulates the variable (which cannot be modified if is 'ref'). Can I use a similar syntax as I'd like, in this case?

Thank you!

**Comment by PeturDarri** [comment]
When defining a `ref` argument in a lambda, you must specify the type and wrap it in parenthesis:
```cs
GenericEventBus<IEvent>.Instance.SubscribeTo<RequestTryChangeStateEvent>((ref RequestTryChangeStateEvent args) =>
{
    var physicsState = args.RequestedPhysicsState;
    TryChangePhysicsState(physicsState);
});
```
Since the type is now specified in the argument, it no longer needs to be specified in the method call, so this can be simplified to:
```cs
GenericEventBus<IEvent>.Instance.SubscribeTo((ref RequestTryChangeStateEvent args) =>
{
    var physicsState = args.RequestedPhysicsState;
    TryChangePhysicsState(physicsState);
});
```
However, I would not recommend subscribing with anonymous functions, because it makes it impossible to unsubscribe unless you save and reuse the same instance in both calls. The only valid use case is if you know this event handler doesn't need to be unsubscribed.

**Comment by EcoEditor** [comment]
Thank you so much for this explanation.
